### ISSUE TITLE
关于base

### ISSUE THREAD

**Issue by unknownbug** [zhchbin/chromium-base#2]
注意: 包含文件:   C:\Users\wf\Desktop\chromiun\chromium-base\src\base/threading/thread_restrictions.h
注意: 包含文件:  C:\Users\wf\Desktop\chromiun\chromium-base\src\base/synchronization/lock_impl.h
[142/142] LINK_EMBED(DLL) base.dll
这个base库编译是整个base库吗？我windows编译出来的有问题啊！（动态库）
谢谢大神！！

**Comment by unknownbug** [comment]
[144/144] LINK_EMBED test_base.exe
FAILED: test_base.exe
D:\bin\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True test_base.exe "D:\bin\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:test_base.exe @test_base.exe.rsp" 1 mt.exe rc.exe "obj\test_base.test_base.exe.intermediate.manifest" obj\test_base.test_base.exe.generated.manifest
LINK : fatal error LNK1181: 无法打开输入文件“base.dll.lib”
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "D:\bin\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'D:\bin\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:test_base.exe @test_base.exe.rsp test_base.exe.manifest.res' returned non-zero exit status 1181
ninja: build stopped: subcommand failed.
没删测试文件的编译，windows下，用的ninja

**Comment by mbbill** [comment]
Seems like you're posting the issue in your own forked repo?
